#======================================================================================================================
# Book settings
#======================================================================================================================
title: Заметки для разработчиков
author: Красников Александр
copyright: 2023–2024
logo: logo.png
email: writer@bookseer.org
description: >- # this means to ignore newlines until "baseurl:"
  Сборник руководств и советов для разработчиков.

# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]

# Auto-exclude files not in the toc
only_build_toc_files: false


#======================================================================================================================
# Information about where the book exists on the web
#======================================================================================================================
repository:
  # Online location of your book
  url: https://github.com/bookseer/dev
  # Optional path to your book, relative to the repository root
  path_to_book: book
  # Which branch of the repository should be used when creating links (optional)
  branch: main


#======================================================================================================================
# Launch button settings
#======================================================================================================================
launch_buttons:
  # The interface interactive links will activate ["classic", "jupyterlab"]
  notebook_interface: "classic"
  # The URL of the BinderHub (e.g., https://mybinder.org)
  binderhub_url: "https://mybinder.org"
  # Add a thebe button to pages (requires the repository to run on Binder)
  thebe: true
  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  jupyterhub_url: ""
  # The URL of Google Colab (https://colab.research.google.com)
  colab_url: ""


#======================================================================================================================
# Execution settings
# See https://jupyterbook.org/content/execute.html
#======================================================================================================================
execute:
  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  execute_notebooks: auto
  # A path to the jupyter cache that will be used to store execution artifacts. Defaults to `_build/.jupyter_cache/`
  cache: ""
  # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  exclude_patterns: []
  # The maximum time (in seconds) each notebook cell is allowed to run.
  timeout: 30
  # If `True`, then a temporary directory will be created and used as the command working directory (cwd),
  # otherwise the notebook's parent directory will be the cwd.
  run_in_temp: false
   # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  allow_errors: false
  # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'
  stderr_output: show


#======================================================================================================================
# Parse and render settings
# See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
#======================================================================================================================
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser.
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist

  # URI schemes that will be recognised as external URLs in Markdown links
  myst_url_schemes: [mailto, http, https]
  # Allow display math ($$) within an inline context
  myst_dmath_double_inline: true


#======================================================================================================================
# HTML-specific settings
#  See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
#======================================================================================================================
html:
  # A path to a favicon image
  favicon: ""
  # A banner announcement at the top of the site.
  announcement: "Сайт находится в разработке"
  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository:
  # must be filled in
  use_edit_page_button: true
  # Whether to add a link to your repository button
  use_repository_button: true
  # Whether to add an "open an issue" button
  use_issues_button: true
  # Continuous numbering across parts/chapters
  use_multitoc_numbering: true
  # Will be displayed underneath the footer
  extra_footer: ""
  # A GA id that can be used to track book views.
  google_analytics_id: ""
  # Whether to include your home page in the left Navigation Bar
  home_page_in_navbar: true
  # The base URL where your book will be hosted. Used for creating image previews and social links.
  baseurl: "https://dev.bookseer.org/"
  analytics:
    google_analytics_id = ''


#======================================================================================================================
# Comments settings
#======================================================================================================================
  comments:
    hypothesis: false
    utterances: false



#======================================================================================================================
# LaTeX-specific settings
#======================================================================================================================
# Define the name of the latex output file for PDF builds
latex:
  # latex_engine  one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  latex_engine: xelatex
  # use sphinx-jupyterbook-latex for pdf builds as default
  use_jupyterbook_latex: true
  latex_documents:
    targetname: book.tex


#======================================================================================================================
# BibLaTex-specific settings
#======================================================================================================================
# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib


#======================================================================================================================
# Sphinx Advanced and power-user settings
#======================================================================================================================
sphinx:
  bibtex_reference_style: author_year  # or label, super, \supercite
  config:  # key-value pairs to directly over-ride the Sphinx configuration
    language: "ru"
    latex_elements:
      preamble: |
        \newcommand\N{\mathbb{N}}
    # https://sphinx-copybutton.readthedocs.io/en/latest/use.html
    # copybutton_prompt_text: r">>> |\.\.\. |\$"
    # copybutton_prompt_is_regexp:  True

  # A list of extra extensions to load by Sphinx (added to those already used by JB).
  extra_extensions:
    - sphinx_inline_tabs
    - sphinx_proof
    - sphinx_togglebutton
  # A list of local extensions to load by sphinx specified by "name: path" items
  local_extensions:
  # A boolean indicating whether to overwrite the Sphinx config (true) or recursively update (false)
  recursive_update: false